version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    restart: always
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - db
  db:
    image: mongo:4.4.4
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
